---
extends:
  - plugin:vue/vue3-essential
  - "@vue/eslint-config-airbnb-with-typescript"
  - "@vue/eslint-config-airbnb-with-typescript/allow-js-in-vue"
  - prettier
plugins:
  - prettier
  - unused-imports
rules:
  quotes:
    - error
    - double
    - allowTemplateLiterals: true
  camelcase: 0
  comma-dangle:
    - error
    - always-multiline
  no-restricted-syntax: 0 # we don't invest in IE11 testing
  no-use-before-define: 0 # a good one, but broken linter
  no-param-reassign:
    - error
    - props: false
  import/no-cycle: 0 # a good one, but broken linter
  import/no-extraneous-dependencies: 0 # not applicable
  no-shadow: 0 # a good one, but broken linter
  no-empty-function: 0 # a good one, but broken linter
  no-useless-constructor: 0 # a good one, but broken linter
  no-console: 0 # not applicable
  consistent-return: 0 # a good one, but broken linter
  object-shorthand: 0 # shorthand works poorly with pycharm
  operator-linebreak: 0 # a good one, but broken linter
  object-curly-newline: 0 # a good one, but broken linter
  no-unused-vars: 0 # a good one, but many exceptions + broken linter
  no-underscore-dangle: 0 # not applicable
  prefer-destructuring: 0 # poor code style
  no-inner-declarations: 0
  import/prefer-default-export: 0
  import/extensions: 0
  prettier/prettier:
    - 1
    -
      trailingComma: all
      printWidth: 93
  unused-imports/no-unused-imports:
    - error
env:
  browser: true
  node: true
globals:
  gtag: true
  google: true
  JSX: true
